# Makefile for building with cross tools for another machine

OETMP = $(OVEROTOP)/tmp

TOOLDIR = $(OETMP)/cross/armv7a/bin

STAGEDIR = $(OETMP)/staging/armv7a-angstrom-linux-gnueabi/usr

CC = $(TOOLDIR)/arm-angstrom-linux-gnueabi-gcc

LIBDIR = $(STAGEDIR)/lib

INCDIR = $(STAGEDIR)/include

LIBS = -L $(LIBDIR)

EXTRA_CFLAGS = -I $(INCDIR)

ifeq ($(strip $(OVEROTOP)),)
    $(error $$OVEROTOP is undefined! Source your profile)
else

include Makefile.common
