TARGET = test
OBJS = main.o lib.o

################################################################################

CFLAGS = -g -Wall -Wextra ${EXTRA_CFLAGS}

${TARGET}:${OBJS}
	${CC} ${CFLAGS} $^ ${LIBS} -o $@

%.o: %.c
	${CC} -c ${CFLAGS} $<

clean:
	rm -f ${TARGET} ${OBJS} *~
